# 感知机的数学原理

**公式:** $$f(x)=sign(w*x+b)$$

其中\begin{equation}
sign(x)=\left\{
\begin{aligned}
+1 &&x \geq 0\\
0 &&x<0
\end{aligned}
\right.
\end{equation}


x是输入，w是权重，b是偏差（偏置项）

# 数学原理很简单，那开始实现一些基本的逻辑运算

+ 与运算
+ 或运算
+ 非运算
+ 异或运算

# 与运算

x1|x2|x1 AND X2
---|---|---|
0|0|0|
0|1|0|
1|0|0|
1|1|1|

对应的不等式为：

b<0

w2+b<0

w1+b<0

w1+w2+b>=0

综上：只要权重满足w1,w2<-b,w1+w2>-b就可以实现与运算；

In [22]:
# 1.与运算
import numpy as np

def AND(x1,x2):
    x=np.array([x1,x2])
    w=np.array([1,1])
    b=-1.5
    y=np.sum(x*w)+b
    if(y>=0):
        return 1
    elif(y<0):
        return 0
    
print(AND(1,1))
print(AND(0,1))
print(AND(1,0))
print(AND(0,0))

1
0
0
0


# 或运算

x1|x2|x1 OR X2
---|---|---|
0|0|0|
0|1|1|
1|0|1|
1|1|1|

对应的不等式为：OR

b<0

w2+b>=0

w1+b>=0

w1+w2+b>=0

综上：只要权重满足w1,w2>=-b就可以实现与运算；

In [23]:
def OR(x1,x2):
    x=np.array([x1,x2])
    w=np.array([1,1])
    b=-0.5
    y=np.sum(x*w)+b
    if(y>=0):
        return 1
    elif(y<0):
        return 0
    
    
print(OR(1,1))
print(OR(0,1))
print(OR(1,0))
print(OR(0,0))

1
1
1
0


# 非运算

x|NOT x
---|---|
0|1|
1|0|


对应的不等式为：

b>=0

w+b<0

综上：只要权重满足w<-b,b>=0就可以实现非运算；

In [24]:
def NOT(x):
    x=np.array([x])
    w=np.array([-1])
    b=0.5
    y=np.sum(x*w)+b
    if(y>=0):
        return 1
    elif(y<0):
        return 0
    
    
print(NOT(1))
print(NOT(0))

0
1


# 异或运算

x1|x2|x1 XOR X2
---|---|---|
0|0|0|
0|1|1|
1|0|1|
1|1|0|



对应的不等式为：

b<0

w2+b>=0

x1+b>=0

w1+w2+b<0

这个不等式无解，所以这就是单层感知机的弊端，不能进行异或运算。

In [26]:
#用多层感知机来解决这个问题
def XOR(x1,x2):
    a=NOT(x1)
    b=NOT(x2)
    X1=AND(a,x2)
    X2=AND(x1,b)
    Y=OR(X1,X2)
    print(Y)
        
XOR(0,0)    
XOR(1,1)
XOR(0,1)
XOR(1,0)

0
0
1
1


In [28]:
from sklearn.neural_network import MLPClassifier
X=[[0,0],[1,1]]
y=[0,1]
clf=MLPClassifier(solver='lbfgs',alpha=0.00001,hidden_layer_sizes=(5,2),random_state=3)
clf.fit(X,y)
print(clf.predict([[2,2],[-1,-2]]))
print(clf.predict_proba([[2,2],[-1,-2]]))

[1 0]
[[1.02563209e-04 9.99897437e-01]
 [9.99999999e-01 1.20358494e-09]]


In [29]:
import pandas as pd
wine = pd.read_csv('./wine.csv', names = ["Cultivator", "Alchol", "Malic_Acid", "Ash", "Alcalinity_of_Ash", "Magnesium", "Total_phenols", "Falvanoids", "Nonflavanoid_phenols", "Proanthocyanins", "Color_intensity", "Hue", "OD280", "Proline"])
wine.head(10)

Cultivator  Alchol  Malic_Acid   Ash  Alcalinity_of_Ash  Magnesium  \
0           1   14.23        1.71  2.43               15.6        127   
1           1   13.20        1.78  2.14               11.2        100   
2           1   13.16        2.36  2.67               18.6        101   
3           1   14.37        1.95  2.50               16.8        113   
4           1   13.24        2.59  2.87               21.0        118   
5           1   14.20        1.76  2.45               15.2        112   
6           1   14.39        1.87  2.45               14.6         96   
7           1   14.06        2.15  2.61               17.6        121   
8           1   14.83        1.64  2.17               14.0         97   
9           1   13.86        1.35  2.27               16.0         98   

   Total_phenols  Falvanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   
5           3.27        3.39                  0.34             1.97   
6           2.50        2.52                  0.30             1.98   
7           2.60        2.51                  0.31             1.25   
8           2.80        2.98                  0.29             1.98   
9           2.98        3.15                  0.22             1.85   

   Color_intensity   Hue  OD280  Proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735  
5             6.75  1.05   2.85     1450  
6             5.25  1.02   3.58     1290  
7             5.05  1.06   3.58     1295  
8             5.20  1.08   2.85     1045  
9             7.22  1.01   3.55     1045

In [40]:
wine.describe().transpose()

count        mean         std     min       25%  \
Cultivator            178.0    1.938202    0.775035    1.00    1.0000   
Alchol                178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity_of_Ash     178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_phenols         178.0    2.295112    0.625851    0.98    1.7425   
Falvanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Cultivator              2.000    3.0000     3.00  
Alchol                 13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Alcalinity_of_Ash      19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_phenols           2.355    2.8000     3.88  
Falvanoids              2.135    2.8750     5.08  
Nonflavanoid_phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix


X = wine.drop('Cultivator',axis=1)
y = wine['Cultivator']
X_train, X_test, y_train, y_test = train_test_split(X, y)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(len(mlp.coefs_))
print(mlp.intercepts_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  if __name__ == '__main__':
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  # Remove the CWD from sys.path while we load stuff.


[[14  0  0]
 [ 0 16  0]
 [ 0  0 15]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        16
           3       1.00      1.00      1.00        15

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

4
[array([ 0.02268954, -0.18597611, -0.05223465, -0.03915678,  0.0920361 ,
        0.28190133,  0.63656087,  0.05534406,  0.51640953,  0.49434338,
        0.10344456,  0.22482859,  0.24794356]), array([ 0.19974845,  0.29001591,  0.55195252, -0.2264305 , -0.10868825,
       -0.25187038,  0.27908955, -0.24704004, -0.08276508,  0.05895807,
        0.14616343,  0.29090088, -0.28079934]), array([ 0.58020092,  0.49080631, -0.36520974, -0.39662484, -0.05502375,
        0.20642197, -0.02144284, -0.4142682 ,  0.58575019,  0.04703106,
        0.01430184, -0.27001323,  0.11880358]), arr